version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www
      - ./.env:/var/www/.env              # Mount the .env file properly
    ports:
      - "8888:9000"                        # Host 8888 → Container 9000
    environment:
      - DB_HOST=34.121.54.220             # Cloud SQL public IP
      - DB_PORT=3306
      - DB_DATABASE=nandvanshi
      - DB_USERNAME=root
      - DB_PASSWORD=

  composer:
    image: composer:latest
    container_name: composer
    working_dir: /var/www
    volumes:
      - .:/var/www

# Removed mysql container since Cloud SQL is being used
