version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: app
    restart: unless-stopped
    volumes:
      - .:/var/www
    working_dir: /var/www
    depends_on:
      - mysql
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    ports:
      - "8888:8888"
    command: php artisan serve --host=0.0.0.0 --port=8888

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: nandvanshi
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
