version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - sqlite
    networks:
      - laravel

  sqlite:
    image: nouchka/sqlite3
    volumes:
      - ./database:/root/db
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
