version: '3.8'

services:
  app:
    build: .
    container_name: laravel-app
    restart: unless-stopped
    environment:
      - APP_ENV=production
    volumes:
      - ./:/var/www
    networks:
      - laravel-network

  webserver:
    image: nginx:alpine
    container_name: laravel-webserver
    restart: unless-stopped
    ports:
      - "7000:7000"  # Using port 7000 for web access
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge