version: '3.8'

services:
  app:
    build:
      context: .
      target: builder
    image: your-registry/laravel-app:${BUILD_ID:-latest}
    container_name: laravel-app
    restart: unless-stopped
    env_file: .env.prod
    volumes:
      - ./:/var/www
      - php_sessions:/var/lib/php/sessions
    networks:
      - laravel-network
    healthcheck:
      test: ["CMD-SHELL", "php artisan inspire"]
      interval: 30s
      timeout: 10s
      retries: 3

  webserver:
    image: nginx:1.23-alpine
    container_name: laravel-webserver
    restart: unless-stopped
    ports:
      - "7000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      app:
        condition: service_healthy
    networks:
      - laravel-network

  db:
    image: mysql:8.0
    container_name: laravel-db
    env_file: .env.prod
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    networks:
      - laravel-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

networks:
  laravel-network:
    driver: bridge

volumes:
  db_data:
  php_sessions: